site:
  production_url: "http://ruby.gelistiriciyiz.biz"
  title: "Ruby Püf Noktaları"
  subtitle: "Ruby ile ilgili Türkçe püf noktaları"
  tag_line: "Gündelik Hayatta Ruby"
  description: "Ruby ile ilgili Türkçe püf noktaları"
  logo: "logo.png"
  cover_image: "cover.jpg"
  social:
    twitter: "ruby_tips_tr"
    # facebook: ""
  company:
    name: "Geliştiriciyiz.biz"
    url: "http://gelistiriciyiz.biz/"
  product:
    name: "GELİŞTİRİCİYİZ.BİZ"
    url: "http://gelistiriciyiz.biz/"
  main_author:
    name: "Uğur Özyılmazel"
    email: "ugurozyilmazel@gmail.com"
    link: "http://ugur.ozyilmazel.com"
    bio: "Yazılım Geliştiricisi"